global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: gateway-service
    static_configs:
      - targets:
          - host.docker.internal:8003
    metrics_path: /metrics

  - job_name: auth-service
    static_configs:
      - targets:
          - host.docker.internal:8001
    metrics_path: /metrics

  - job_name: catalog-service
    static_configs:
      - targets:
          - host.docker.internal:8004
    metrics_path: /metrics

  - job_name: cart-service
    static_configs:
      - targets:
          - host.docker.internal:8005
    metrics_path: /metrics

  - job_name: order-service
    static_configs:
      - targets:
          - host.docker.internal:8006
    metrics_path: /metrics

  - job_name: inventory-service
    static_configs:
      - targets:
          - host.docker.internal:8007
    metrics_path: /metrics

  - job_name: notification-service
    static_configs:
      - targets:
          - host.docker.internal:8008
    metrics_path: /metrics
